common-obj-$(CONFIG_PCI) += ipc_pcie_sizer.o
common-obj-$(CONFIG_PCI) += downstream_pcie_connection.o
common-obj-$(CONFIG_PCI) += requesters_table.o
common-obj-$(CONFIG_EXTERNAL_PCI) += external_pci.o
